### ISSUE TITLE
Results Telomerase Activity Prediction:

### ISSUE THREAD

**Issue by NNoureen** [AlexsLemonade/OpenPBTA-manuscript#105]
#### What section of the manuscript should be updated?

Results section

#### Proposed changes

_What changes need to be made and/or what details are missing?_
_Explain your rationale for the update._
_Please include a level of detail that will allow another participant to make the update._

This issue is to track the addition of a telomerase activity prediction section to the results section of the manuscript.

#### Relevant literature

_If there is relevant scientific literature, put links to those items here._
@doi:https://doi.org/10.1101/2020.05.21.109249

**Comment by jaclyn-taroni** [comment]
Closed via #108.
