### ISSUE TITLE
Updated manuscript: glioma brain region method

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#106]
#### What section of the manuscript should be updated?
https://alexslemonade.github.io/OpenPBTA-manuscript/#clinical-data-harmonization

_Add the section (and subsection) needing an update._
Table describing clinical attributes.

#### Proposed changes

_What changes need to be made and/or what details are missing?_
Table is missing some information around how glioma brain region was defined.

_Explain your rationale for the update._
Missing information - needs to be filled in.

_Please include a level of detail that will allow another participant to make the update._
Below is the logic that was used for this (informed by Dr. Angela Waanders):

```
gliomas$glioma_brain_region <- ifelse(grepl("Thalamus|Pons|Spinal Cord|Brain Stem|Midbrain|Hippocampus|Medulla", gliomas$primary_site), "midline", 
                             ifelse(grepl("Lobe|Cerebellum", gliomas$primary_site), "hemispheric", 
                                    ifelse(grepl("Blood", gliomas$primary_site), "blood", "other")))
gliomas$glioma_brain_region <- ifelse(grepl("Basal Ganglia|Posterior Fossa|Hippocampus;Temporal|Temporal Lobe;Thalamus", gliomas$primary_site), "mixed", paste0(gliomas$glioma_brain_region))
```

#### Relevant literature

_If there is relevant scientific literature, put links to those items here._
NA

**Comment by allisonheath** [comment]
I believe these were further reviewed by the CCI group, just wanted to make sure the same mappings were kept upon that review @jainpayal022 @aadamk @baileyckelly ?

**Comment by aadamk** [comment]
@baileyckelly - during an HGG meeting, you mentioned brain region as resolved. Has the mapping above remained the same or have there been any alterations?

**Comment by jharenza** [comment]
> @baileyckelly - during an HGG meeting, you mentioned brain region as resolved. Has the mapping above remained the same or have there been any alterations based on discussion with Cassie?

The mappings have expanded from hemispheric, midline, and mixed to many other, and additionally are being named `CNS_region` in [V17](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/764). 

@baileyckelly or @aadamk - would one of you want to update/add a table of the new mappings (probably easiest) to the manuscript methods?

**Comment by aadamk** [comment]
@jharenza 
Updated mappings are attached based on latest v17 histologies candidate file [here](https://docs.google.com/spreadsheets/d/1gvcu6QdaRfLbIb_agFlaMt-Vvr3Wmx0MJdCZhcDUiVg/edit#gid=1618623771). 

[OpenPBTAv17_CNSmapping.txt](https://github.com/AlexsLemonade/OpenPBTA-manuscript/files/5278180/OpenPBTAv17_CNSmapping.txt)

**Comment by jharenza** [comment]
I am working on this today

**Comment by jharenza** [comment]
close with #126
