### ISSUE TITLE
Updated manuscript: Add more background on consensus mutation calls

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-manuscript#112]
#### What section of the manuscript should be updated?

The `Somatic mutation`, `Consensus SNV Calling` section of the methods paper.

#### Proposed changes

Once https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/745 is finalized, the summarized and manuscript-pertinent information from the README should also be added to the manuscript. (It's not clear what that will be at this time). 

But in general, we need more information about why we decided to use 3 out of 3 callers as a decision for including a mutation in the consensus file. This ultimately affects downstream analyses including subtyping labels, so having more clearly explained rationale behind that decision is needed. 

#### Relevant literature

The Lancet methods paper: https://www.nature.com/articles/s42003-018-0023-9#Sec28

**Comment by sjspielman** [comment]
@jaclyn-taroni It seems to me this content has actually already been integrated into Methods, based on my reading of [this section](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/06.methods.md#consensus-snv-calling).

Copied here:

>We examined the variant allele frequencies produced by each caller and compared their overlap with each other [[62](https://alexslemonade.github.io/OpenPBTA-manuscript/#ref-Ob2wQ9wX)]. VarDict calls included many variants that were not identified by other callers [[63](https://alexslemonade.github.io/OpenPBTA-manuscript/#ref-Z1i0sjNH)], while the other callers produced results that were relatively consistent with one another. Many of these VarDict-specific calls were variants with low allele frequency [[64](https://alexslemonade.github.io/OpenPBTA-manuscript/#ref-tkwfe0u6)]. We termed mutations shared among the other three callers (Strelka2, Mutect2, and Lancet) to be consensus mutation calls and dropped VarDict due to concerns about it calling a large number of false positives. In practice, because our filtered set was based on the intersection of these three sets and because VarDict called nearly every mutation from the other three callers plus many that were unique to it, the decision to not consider VarDict calls has little impact on the results.

Would you agree?

**Comment by jaclyn-taroni** [comment]
Yup!
