### ISSUE TITLE
Updated manuscript: Add @sjspielman as an author

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#114]
#### What section of the manuscript should be updated?

This issue is to track the addition of @sjspielman as an author. We are planning to use the [CRediT taxonomy](https://www.cell.com/pb/assets/raw/shared/guidelines/CRediT-taxonomy.pdf) for author contributions. Additionally, we'll need to add contact info (email, Twitter, etc.) to [`content/metadata.yaml`](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/metadata.yaml).

Regarding analysis modules authored by @sjspielman: currently, the GSVA results are included in a figure in the manuscript. I believe you reviewed survival analyses and telomerase activity as well, but I will let you fill in the details!

See #107 and #110 for reference.

**Comment by sjspielman** [comment]
Hi @jaclyn-taroni , sorry for the delay here. Which will make your life easier - 
1) I can submit a PR with the info directly added to the metadata
2) Suggest roles and info to include in this issue and you add to metadata

**Comment by jaclyn-taroni** [comment]
Number 1 sounds good to me, thanks!

**Comment by jaclyn-taroni** [comment]
Closed via #120
