### ISSUE TITLE
Submission: Does the journal require employees of funders to state COI?

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#119]
When we submit, we may need to state that some authors (@jashapiro, @cansavvy, @cbethell and @jaclyn-taroni) are employees of Alex's Lemonade Stand Foundation, a funder and sponsor of this research. This will depend on the journal/publisher's policy.

**Comment by sjspielman** [comment]
This has been integrated into the manuscript, including for @sjspielman.

+ https://github.com/AlexsLemonade/OpenPBTA-manuscript/commit/ef14e1fc1ec155c865d8a0f66ff442ffda23ced7
+ https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/221
