### ISSUE TITLE
Handling supplementary tables/files

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#124]
Manubot only appears to support Markdown tables. It is can sometimes be desirable to link to individual supplementary items (e.g., TSV that contains some set of values) that will be available on GitHub. What is the best way to link to these items?

**Comment by jharenza** [comment]
we are adding tables in https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/tables and figures in https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/figures/pdfs/supp
