### ISSUE TITLE
Updated manuscript: Integrated and harmonised diagnosis description. 

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenPBTA-manuscript#129]
#### What section of the manuscript should be updated?

https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#clinical-data-harmonization

#### Proposed changes

The changes in v18 (as implemented in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/870, etc.) restructure the way the diagnosis columns are composed, and this needs to be reflected in the methods, especially as this section serves as the main documentation for the contents of the pbta-histologies.tsv file.

**Comment by jharenza** [comment]
closed with #183
