### ISSUE TITLE
Updated manuscript: SNV hotspots

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-manuscript#134]
#### What section of the manuscript should be updated?

_Add the section (and subsection) needing an update._
Somatic Mutation Calling
New Sub section: `Gather SNV hotspots`

#### Proposed changes

_What changes need to be made and/or what details are missing?_
We added a analysis to added back hotspots https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/hotspots-detection

_Explain your rationale for the update._

This analysis helps to check for overlaps within hotspots in MSKCC cancer hotspots v2 file downloaded as well as use a TERT promoter region overlap to gather known cancer mutations.

_Please include a level of detail that will allow another participant to make the update._

#### Relevant literature

_If there is relevant scientific literature, put links to those items here._

**Comment by jharenza** [comment]
closed with #138
