### ISSUE TITLE
Updated manuscript: TP53 alteration analyses

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-manuscript#137]
#### What section of the manuscript should be updated?

_Add the section (and subsection) needing an update._
Not sure .. Clinical Data Harmonization?

#### Proposed changes

_What changes need to be made and/or what details are missing?_
https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/tp53_nf1_score

**TP53 altered - loss**, if :

 - A sample contains a TP53 hotspot SNV mutation. (Cancer hotspot database and downloadable file available). Please also crosscheck that all mutations from this table are included.
 - A sample contains two TP53 alterations, suggesting (but not confirming) that both alleles are affected (SNV+SNV, (CNV or SV) + SNV).
 - A sample contains one alteration (SNV or (CNV or SV)) + has cancer_predispositions == "Li-Fraumeni syndrome", suggesting there is a germline variant in addition to the somatic variant we observe.
 - A sample does not have a TP53 alterations, but has cancer_predispositions == "Li-Fraumeni syndrome" and TP53 classifier score for matched RNA-Seq > 0.5 (or higher cutoff we decide upon later).
 
 Note: CNV and SV will be considered as the same event, but we will be adding SV_counts and SV.type to the altered status output file
 
**TP53 altered - activated**, if:

- A sample contains one of the two TP53 activating mutations R273C and R248W. Reference and reference.

_Explain your rationale for the update._
_Please include a level of detail that will allow another participant to make the update._

#### Relevant literature

_If there is relevant scientific literature, put links to those items here._

**Comment by jharenza** [comment]
@runjin326 will work on this

**Comment by runjin326** [comment]
@kgaonkar6, quick question: do we have citations for the functional domain files (`hotspot_Chen_2006.tsv`) used in the analyses - I tried googling but couldn't find it?  Also the hotspot database (`hotspot_v2.xsl) is from  https://p53.iarc.fr ?

**Comment by kgaonkar6** [comment]
Hi @runjin326 , thanks for pointintg out that `hotspot_Chen_2006.tsv` info is missing , I'll update the README. 

I traced the links for the tables in the original issue https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/837 and added the filenames 
1. A sample contains a _TP53_ hotspot SNV mutation. ([Cancer hotspot database](https://www.cancerhotspots.org/#/home) and [hotspot_v2.xls](https://www.cancerhotspots.org/#/download) available). Please also crosscheck that all mutations from [hotspot_Chen_2006.tsv](https://www.nature.com/articles/4401904/tables/1) are included.

**Comment by runjin326** [comment]
Thanks so much @kgaonkar6! Super helpful!

**Comment by jaclyn-taroni** [comment]
Closed via #145
