### ISSUE TITLE
Updated manuscript: Add CRC/Consortium author list

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#141]
#### What section of the manuscript should be updated?
Administrative or Back matter ? cc @jaclyn-taroni 

#### Proposed changes

Add PNOC and CBTN consortia author lists with PIs and CRC (clinical research coordinator) names. This will be a list of members which will go into its own section for now.

#### Relevant literature
NA

**Comment by jaclyn-taroni** [comment]
`content/06.administrative.md` under its own header seems pretty reasonable to me for now.

**Comment by jharenza** [comment]
Additional list for CBTN: https://chop365-my.sharepoint.com/:x:/g/personal/stefankies_chop_edu/EbX_Vx-5RddKgL2Oeb8YtmEBWyUu4EGSiOlQUD_4Io4RSg?email=HARENZAJ%40chop.edu&e=4%3AJ2znGa&at=9&CID=1eaa0fec-87a7-1a17-c119-235b97ed45b2
