### ISSUE TITLE
Updated manuscript: make sure all abbreviations are spelled out at first instance

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#166]
#### What section of the manuscript should be updated?
Once we have more of the paper merged, go through and make sure all instances of abbreviations are spelled out at first instance and only done once. For example, we have many things spelled out/abbreviated in methods currently (WGS, WXS, etc) which will be later instances than the first use since the results section will come first and is now being added.

#### Proposed changes

See above

#### Relevant literature

NA

**Comment by jharenza** [comment]
@runjin326 or I will take this on once #139 is completed

**Comment by sjspielman** [comment]
Going to set this as part of the revision Epic, since it was not necessarily completed for initial submisison.

**Comment by jharenza** [comment]
completed as best we could during final resubmission
