### ISSUE TITLE
Updated manuscript: how to handle supplemental figure and table numbering with internal links

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#172]
#### What section of the manuscript should be updated?
The figures seem to be numbered automatically, rather than by numbers assigned in title text. For example, Figure S1's embedded link shows as `Figure 9` [here](https://alexslemonade.github.io/OpenPBTA-manuscript/#crowd-sourced-somatic-analysis-to-create-an-open-pediatric-brain-tumor-atlas)
#### Proposed changes

To make things easy, I would suggest we can just leave out supplemental figure and table embedded links, but wanted to get other opinions from @jaclyn-taroni and @jashapiro as to whether this is OK and/or it is worth figuring this out in manubot.

#### Relevant literature

NA

**Comment by jharenza** [comment]
@jashapiro I vaguely remember you responding to this, but I cannot find it currently - do you recall?

**Comment by jashapiro** [comment]
I think my only response was that there is no automated way to handle this in manubot, based on discussion here: https://github.com/manubot/rootstock/issues/225.

**Comment by jharenza** [comment]
got it, thanks!

**Comment by jharenza** [comment]
We decided we will not embed links for these.
