### ISSUE TITLE
Reword co-occurence events in terms of OR/CI?

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#173]
Pertaining to this discussion:

The percentages here and below are not really defined. I think it might makes sense to briefly define or reference what the calculation is, as I do not think it is obvious or intuitive from the text.

_Originally posted by @jashapiro in https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/167#discussion_r747819069_

@jashapiro suggested we might want to use OR and CIs instead of percentages, since the calculations might be a bit complicated to explain succinctly. @runjin326 will work on adding these in the analysis repo.

**Comment by jharenza** [comment]
@runjin326 will take on this issue

**Comment by runjin326** [comment]
@jharenza - just want to clarify: is this to update the results section or the methods section?

**Comment by jharenza** [comment]
> @jharenza - just want to clarify: is this to update the results section or the methods section? 

Results!

**Comment by jharenza** [comment]
done in #192
