### ISSUE TITLE
Updated manuscript: Update Stephanie's author credentials

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#179]
#### What section of the manuscript should be updated?

Authorship affiliation

#### Proposed changes

+ Stephanie is now at CCDL
+ BUT, Stephanie was also funded by CCDL while at Rowan, and this information seems maybe important to not delete?
+ Does this mean two affiliations?

**Comment by jharenza** [comment]
closed with #182
