### ISSUE TITLE
Update molecular signatures methods

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#193]
#### What section of the manuscript should be updated?

The **Molecular Signatures** method section is out of date and should be updated. We now use `deconstructSigs` to assess exposures to 8 known adult CNS signatures, identified [in this reference](https://www.nature.com/articles/s43018-020-0027-5), and _not_ COSMIC and Alexandrov due to sample size constraints.

**Comment by jharenza** [comment]
updated with #195
