### ISSUE TITLE
Add DOIs for OpenPBTA -analysis and -manuscript repos

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#196]
As discussed in issue #175 and PR #190 ([this comment](https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/190#issuecomment-1072690282)), DOIs need to be added for `OpenPBTA-analysis` and `OpenPBTA-manuscript` repos once we are able to index in zenodo (or similar).

**Comment by jaclyn-taroni** [comment]
I'm working on this right now. The DOI for the release of the analysis repository will be: `10.5281/zenodo.7042013`.

**Comment by jharenza** [comment]
Updated analysis repo doi in #418. We decided last time not to make one for manuscript repo.
