### ISSUE TITLE
Updated manuscript: add survival module methods? 

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#209]
#### What section of the manuscript should be updated?

methods

#### Proposed changes

We have run various survival analysis models with a number of covariates - perhaps we should add to the methods a generalized statement of what we used and when (eg univariate vs multivariate). cc @jaclyn-taroni - thoughts?

**Comment by jaclyn-taroni** [comment]
This addition only makes sense to me if we expect any survival analysis to be included in the paper. It is not clear to me that that is the case currently. I am all for making sure that this is documented in the analysis repository documentation! I just think it might be confusing for a reader if the analyses are not in the manuscript.

**Comment by jharenza** [comment]
> This addition only makes sense to me if we expect any survival analysis to be included in the paper. It is not clear to me that that is the case currently. I am all for making sure that this is documented in the analysis repository documentation! I just think it might be confusing for a reader if the analyses are not in the manuscript.

Agreed, so holding off for now.

**Comment by jharenza** [comment]
We will want to add these now that we have agreed on these analyses over in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1276

**Comment by jharenza** [comment]
done in #254
