### ISSUE TITLE
Updated manuscript: quantification and statistical analysis section

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#210]
#### What section of the manuscript should be updated?

methods - specifically `QUANTIFICATION AND STATISTICAL ANALYSIS`

#### Proposed changes

Currently, we do not have anything in this section. Looking back at [my PDX paper](https://www.cell.com/cell-reports/pdfExtended/S2211-1247(19)31268-9), it looks like I moved the entire methods for the more quantitative/statistical analyses to this section. Should we do that here as well, or should we pull out the specifics and put them in this section. For example, things such as below can probably be moved:
- Quantification of Telomerase Activity using Gene Expression Data
- Prediction of participants' genetic sex
- PBTA Tumor Mutation Burden
- TCGA Tumor Mutation Burden
- Mutational Signatures
- Dimension reduction
- Gene Set Variation Analysis
- Immune Profiling/Deconvolution
- Gene Expression Matrices with Unique HUGO Symbols
- Abundance Estimation
- Chromothripsis Analysis (WGS samples only)
- Focal Copy Number Calling
- Consensus CNV Calling
- Recurrently mutated genes and co-occurrence of gene mutations
- Consensus SNV Calling
- RNA Fusion Calling and Prioritization

It looks like I reserved methods for primary methods and this section for the analyses performed. Do we want to use that as a guide?

#### Relevant literature

thoughts @jaclyn-taroni and @sjspielman ?

**Comment by jharenza** [comment]
Also, during this PR, we can probably remove section "additional resources", which follows this one.

**Comment by jaclyn-taroni** [comment]
Going to start by [linking the guide to STAR Methods](https://els-jbs-prod-cdn.jbs.elsevierhealth.com/pb-assets/journals/research/cell/methods/Methods_Guide_general-1622124325553.pdf).

**Comment by jaclyn-taroni** [comment]
> It looks like I reserved methods for primary methods and this section for the analyses performed. Do we want to use that as a guide?

This seems like a reasonable approach. I might leave sections on any consensus calling in `METHODS DETAILS` as that's where much of our analyses _begin_ (i.e., with the output of the consensus modules).

**Comment by jharenza** [comment]
done in #222
