### ISSUE TITLE
Updated manuscript: add software and versions / sources to Key Resources table

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#217]
#### What section of the manuscript should be updated?

key resources, within the methods

#### Proposed changes

Add software, versions, and references/links

#### Relevant literature

references are within methods - needs to be copied to this table

**Comment by jaclyn-taroni** [comment]
In the project Docker container, run the following in R to get the R packages installed as a TSV file

```r
data.frame(installed.packages()[, 3]) %>%
  readr::write_tsv("r_packages.tsv")
```

**Comment by jharenza** [comment]
just for reference, I used (column 3 is just the version, and column 1 had the package 😄 )
```r
> data.frame(installed.packages()[, c(1,3)]) %>%
+     readr::write_tsv("kitematic/scratch/r_packages.tsv")
```

**Comment by jharenza** [comment]
@jaclyn-taroni and @sjspielman - there are 434 packages being used in the R docker image, so I listed them [here](https://docs.google.com/spreadsheets/d/11mvkikvSISfRgu7LPcTPUpxbA2ZZFA7YBeXwznsDCAU/edit#gid=0&fvid=1938762632) and started to reference the big ones we should cite. Can you take a once over this and see if I missed any big ones, and also weigh in (there is a column for include yes/no) whether you think we should add things like the reference genome, variant annotator, etc? I also used the "OpenPBTA Docker Image" as the "Identifier". Looking back, the source is usually a citation or manufacturer and the identifier is a URL (repo) or catalog number. Since we have the versions all installed within our docker image, I think it makes sense to list that as the identifier.

Note: I also have to add things such as the variant callers, etc, but again will stay basic here and do major algorithms because every dependency is also in a docker image.

**Comment by sjspielman** [comment]
If we are going to be over 10 anyways, I don't see why we shouldn't include everything, but we can have packages/softwares that are specifically mentioned in the main text at the top of the list. We should be able to automate many of the citations for R packages as well, assuming authors provided appropriate citations with their R package.

We may want to separate this two into a few sheets as well - 
+ R packages
+ Command line tools
+ Reference genomes etc.

**Comment by jaclyn-taroni** [comment]
I think listing the Docker image and then including supplemental material that allows any reader to look up anything they might want to know easily (that is, without pulling the image themselves) makes sense.

**Comment by jharenza** [comment]
> Something we'll need to be aware of - not all analysis modules will be in the manuscript, so this means we can't automatically assume what's in the Docker image is exactly the same as the key resources table.

yeah, I also thought of this - I don't know if there is an easy way to determine what was used for the manuscript or what wasn't, but I suppose we can just print everything and make a disclaimer

**Comment by sjspielman** [comment]
Getting started on this now, and I think "I suppose we can just print everything and make a disclaimer" is the answer for now! 

That said, I think it would be good to indicate in the analysis repo which modules actually are in the manuscript. I'll open an issue for that next door.

**Comment by sjspielman** [comment]
Filed in analysis repo: [AlexsLemonade/OpenPBTA-analysis#1289](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1289)

**Comment by jharenza** [comment]
This is now a supplementary table and is mentioned in the KR table in #242
