### ISSUE TITLE
Check RNA-Seq workflow link

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#224]
Possibly we need to update the link for the RNA-Seq workflow, per below.

Might want to be explicit which workflow file this was? I seem to remember (?) we used a deprecated one: https://github.com/kids-first/kf-rnaseq-workflow/tree/master/workflow/deprecated

_Originally posted by @sjspielman in https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/222#discussion_r838757044_

**Comment by sjspielman** [comment]
For reference this is where I noticed some links needed updating in the repo. 
https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1236

**Comment by jharenza** [comment]
This should be the link, https://github.com/d3b-center/OpenPBTA-workflows/blob/master/cwl/kfdrc_RNAseq_workflow.cwl, and I will update

**Comment by jharenza** [comment]
closed in #234
