### ISSUE TITLE
Add Yang Yang to author list

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#228]
Contributed the initial chromothripsis module code, which falls under the "formal analysis" and "software" contribution categories. 

@Yangyangclover, can you let us know your preferred email address to include in the author list for this manuscript? Thanks!!

**Comment by yangyangclover** [comment]
yangyangclover@gmail.com
Thank you so much!

**Comment by sjspielman** [comment]
Thanks, @yangyangclover !
