### ISSUE TITLE
Update Fig 1 and S1 captions

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#237]
Panels Figure 1A and Figure S1 (single-panel figure) were created with Biorender. We need to therefore add this (with link!) to the captions for these figures:
**Created with [BioRender.com](http://biorender.com/)**

**Comment by jharenza** [comment]
this is in S1 (not hyperlinked, though). good catch on Figure 1A.

**Comment by sjspielman** [comment]
I was just exporting the licenses for publication from Biorender and saw this! I have the licenses in my google drive when we need them.

**Comment by jharenza** [comment]
updated in #238 but fyi, since figure 1's legend is embedded within a link to display the legend, I could not hyperlink biorender.com

**Comment by jharenza** [comment]
closed with #238
