### ISSUE TITLE
Updated manuscript: add Peter Madsen as author

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#248]
#### What section of the manuscript should be updated?

yaml authorship file

#### Proposed changes

Add Peter Madsen @pmadsen101 for Editing: https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/157

#### Relevant literature

_If there is relevant scientific literature, put links to those items here._

**Comment by pmadsen101** [comment]
ORCID: 0000-0001-9266-3685
Twitter: @petermadsenmd

**Comment by jaclyn-taroni** [comment]
Thanks for posting this info @pmadsen101! I'm going to reopen this so we can use it to track it the addition to the manuscript.

**Comment by jharenza** [comment]
closed with #251
