### ISSUE TITLE
Updated manuscript: Update PBTA-workflows doi and release #

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#270]
#### What section of the manuscript should be updated?

STAR methods, Key Resources table

#### Proposed changes

Update DOI: [![DOI](https://zenodo.org/badge/225902612.svg)](https://zenodo.org/badge/latestdoi/225902612) and release number to v1.0.2 due to changes after adding AnnotSV, FusionAnnotator, and removing GISTIC

#### Relevant literature

NA

**Comment by jharenza** [comment]
Note, this is added in #296

**Comment by sjspielman** [comment]
While reviewing #296, I had a question about this issue - is this updated workflow version the same version that was used to create the V22 data release?

**Comment by jharenza** [comment]
Yes, no data was rerun for v22. We were just missing these tools' code!

**Comment by jharenza** [comment]
I just updated this to 1.0.3, adding ANNOVAR, Snpeff, and clinvar filtering

**Comment by jharenza** [comment]
updated in #299
