### ISSUE TITLE
Update Figure 1 caption

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#271]
Once https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1403 is completed for 1B, we need to update the caption accordingly.

**Comment by sjspielman** [comment]
From this comment: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1456#discussion_r903967450

The caption should further be updated to indicate that _only samples with available descriptors_ were included in panel 1B.

**Comment by jharenza** [comment]
closed with #280
