### ISSUE TITLE
Check tumor purity values

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#272]
In the results line 204, we write: 
> In addition, the tumor purity of these two LFS samples was low (16% and 37%, respectively), suggesting the classifier may require a certain level of tumor purity to achieve good performance, as we expect _TP53_ to be intact in normal cells. 

I am having trouble finding the source of these two numbers so we will want to confirm them and ensure they are reflected somewhere in the code/data.

**Comment by jharenza** [comment]
They are in the histologies file under tumor_fraction, so would be in supp table 1
