### ISSUE TITLE
Convert manuscript to Word Document

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#298]
This issue is being created to assign and track the manuscript conversion to a Word document, because the original issue tracking this #220 was converted to an Epic. This issue will therefore go into that epic.

We will convert the manuscript to a Word doc, rather than a Google doc, because Word will allow us to have a clear "original" version that we can compare edits back to, without worrying we may miss edits on a shared google doc and/or lose the original text once shared over google.

**Comment by jharenza** [comment]
I think we can close this now, since we have the output.
