### ISSUE TITLE
Convert reference style to Cell format

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#304]
#### What section of the manuscript should be updated?

References should be formatted for _Cell_ prior to submission

#### Proposed changes

This [page](https://github.com/manubot/manufesto/blob/master/USAGE.md#custom-formatting) describes how to update references to a specific citation style, specifically, [this](https://github.com/manubot/rootstock/issues/242#issuecomment-507688339) comment.

Looks like the _Cell_ citation style can be found [here](https://github.com/citation-style-language/styles/blob/master/cell.csl) or [here](https://www.zotero.org/styles?q=Cell&dependent=0).

**Comment by jashapiro** [comment]
A more up to date reference may be https://github.com/manubot/rootstock/blob/main/USAGE.md#custom-formatting

**Comment by jashapiro** [comment]
This is done in a branch, but stacked on #306, so waiting for that to go in first.  https://github.com/jashapiro/OpenPBTA-manuscript/tree/jashapiro/cite-updates
