### ISSUE TITLE
Paper submission

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#307]
This Epic is to track items that need to be completed for submission to _bioRxiv_ and _Cell Genomics_, but can be pursued in parallel or after we get comments back from all co-authors.

**Comment by jharenza** [comment]
Note: I will plan to submit to Cell Genomics either Tuesday, Sep 6 or Wed, Sep 7. cc @jaclyn-taroni @jashapiro @sjspielman
