### ISSUE TITLE
Update FDA/website references

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#310]
From this comment, there are a few website references which we should update:

Hi @jashapiro - these changes look good. The Cell format and biorxiv changes look as expected.

I did notice some other refs we will want to update, but do not need to do it here and I can put this into a new ticket. Perhaps, if any, you can update the two arxiv references here.

https://paperpile.com/s/cell-citation-style/

- Website link only - I think this one should possibly be a link within the text
PNOC008: A Pilot Trial Testing the Clinical Benefit of Using Molecular Profiling to Determine an Individualized Treatment Plan in Children and Young Adults with High Grade Glioma (Excluding Diffuse Intrinsic Pontine Glioma) – Pacific Pediatric Neuro-Oncology Consortium.

- Author to add: `National Cancer Institute`
(2008). Childhood Medulloblastoma and Other Central Nervous System Embryonal Tumors Treatment (PDQ®)–Health Professional Version - NCI.

- ~~Author to add: `The St. Jude Children's Research Hospital–Washington University Pediatric Cancer Genome Project.`
(2014). The genomic landscape of diffuse intrinsic pontine glioma and pediatric non-brainstem high-grade glioma. Nat Genet 46, 444–450. https://doi.org/10.1038/ng.2938.~~

- `NA` author, remove NA
&NA; (2012). FDA Approves Pediatric Formulation of Afinitor for Children with Subependymal Giant Cell Astrocytoma. Oncology Times 34, 22. https://doi.org/10.1097/01.cot.0000421359.88140.a8.

- Should these have titles un-hyperlinked and have direct web links if a website and not a paper?? Assuming this happens if we did not use doi
  - Boettiger, C., and Eddelbuettel, D. (2017). An Introduction to Rocker: Docker Containers for R (arXiv).
  - Li, H. (2013). Aligning sequence reads, clone sequences and assembly contigs with BWA-MEM (arXiv).
  - Mantel, N. (1966). Evaluation of survival data and two new rank order statistics arising in its consideration. Cancer Chemother Rep 50, 163–170.
  - Merkel, D. (2014). Docker: lightweight Linux containers for consistent development and deployment. Linux Journal 2014, 2:2.
  - Parker, H. (2017). Opinionated analysis development (PeerJ).
  - Research, C. for D.E. and (2018). FDA approves everolimus for tuberous sclerosis complex-associated partial-onset seizures. FDA.
  - Research, C. for D.E. and (2019a). FDA approves larotrectinib for solid tumors with NTRK gene fusions. FDA.
  - Research, C. for D.E. and (2019b). FDA approves entrectinib for NTRK solid tumors and ROS-1 NSCLC. FDA.
  - Research, C. for D.E. and (2020a). FDA approves pembrolizumab for adults and children with TMB-H solid tumors. FDA.
  - Research, C. for D.E. and (2020b). FDA approves selumetinib for neurofibromatosis type 1 with symptomatic, inoperable plexiform neurofibromas. FDA.
bio

- A few refs have html italic/superscript tags, not sure if that is an issue, just pointing out here:
  - Duchemann, B., Naigeon, M., Auclin, E., Ferrara, R., Cassard, L., Jouniaux, J.-M., Boselli, L., Grivel, J., Desnoyer, A., Danlos, F.-X., et al. (2022). CD8<sup>+</sup>PD-1<sup>+</sup> to CD4<sup>+</sup>PD-1<sup>+</sup> ratio (PERLS) is associated with prognosis of patients with advanced NSCLC treated with PD-(L)1 blockers. J Immunother Cancer 10, e004012. https://doi.org/10.1136/jitc-2021-004012.
  - Guha, T., and Malkin, D. (2017). Inherited<i>TP53</i>Mutations and the Li–Fraumeni Syndrome. Cold Spring Harb Perspect Med 7, a026187. https://doi.org/10.1101/cshperspect.a026187.
  - Pfaff, E., Remke, M., Sturm, D., Benner, A., Witt, H., Milde, T., von Bueren, A.O., Wittmann, A., Schöttler, A., Jorch, N., et al. (2010). <i>TP53</i> Mutation Is Frequently Associated With <i>CTNNB1</i> Mutation or <i>MYCN</i> Amplification and Is Compatible With Long-Term Survival in Medulloblastoma. JCO 28, 5188–5196. https://doi.org/10.1200/jco.2010.31.1670.
  - Ramkissoon, L.A., Horowitz, P.M., Craig, J.M., Ramkissoon, S.H., Rich, B.E., Schumacher, S.E., McKenna, A., Lawrence, M.S., Bergthold, G., Brastianos, P.K., et al. (2013). Genomic analysis of diffuse pediatric low-grade gliomas identifies recurrent oncogenic truncating rearrangements in the transcription factor <i>MYBL1</i>. Proc. Natl. Acad. Sci. U.S.A. 110, 8188–8193. https://doi.org/10.1073/pnas.1300252110.

- ~~This one has some odd author attributes, probably needs a manual update
Justin Guinney [Aut, Cre], Robert Castelo [Aut], Joan Fernandez[Ctb] (2017). GSVA. https://doi.org/10.18129/b9.bioc.gsva.~~

_Originally posted by @jharenza in https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/308#pullrequestreview-1071423100_

**Comment by jashapiro** [comment]
Tracking from the previous thread:
> > NA author, remove NA
&NA; (2012). FDA Approves Pediatric Formulation of Afinitor for Children with Subependymal Giant Cell Astrocytoma. Oncology Times 34, 22. https://doi.org/10.1097/01.cot.0000421359.88140.a8.

> Should we change this to link to an FDA page as well, for consistency? Or can we cite all of these from a meta-source like https://www.fda.gov/about-fda/oncology-center-excellence/pediatric-oncology-drug-approvals?

I think I would prefer to merge all of the citations in this paragraph into one for conciseness. The pediatric drug approval database above seems the most logical to me. I guess a remaining question is whether we would want to trim the paragraph to not name each of the drugs, or leave it as is. Thoughts on this @jharenza ?

**Comment by jharenza** [comment]
>I think I would prefer to merge all of the citations in this paragraph into one for conciseness. The pediatric drug approval database above seems the most logical to me. 

Fine by me!

>I guess a remaining question is whether we would want to trim the paragraph to not name each of the drugs, or leave it as is.

I had this question from someone else, but prefer they stay. This section was also reviewed by a neurosurgeon and we concluded to let's see if any of the domain experts want to trim this when we send it out. I think it is good information to have at a glance, esp if we remove the specific links.

**Comment by jashapiro** [comment]
Most of this was completed with #321, with the remaining updates, I think, limited to the issue copied to #358
