### ISSUE TITLE
Updated manuscript: extra commas in contributions

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#313]
#### What section of the manuscript should be updated?

Author contributions - Something bizarre is happening in that each letter is comma-separated for contributions of some authors.
<img width="885" alt="Screen Shot 2022-08-14 at 3 25 13 PM" src="https://user-images.githubusercontent.com/207034/184551902-250956d2-0bcd-4cb0-8b23-f31d97c518ae.png">

#### Proposed changes

Not sure yet

**Comment by cgreene** [comment]
I wrote that code. Nearly certain I used commas to join the list. However, a list with only one element would be a string and it'd join those too... Probably a quick fix :)

**Comment by cgreene** [comment]
It's this line: https://github.com/AlexsLemonade/OpenPBTA-manuscript/blame/master/content/05.administrative.md#L16
