### ISSUE TITLE
Updated manuscript: updated author emails

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#315]
#### What section of the manuscript should be updated?

Update emails for:
- [x] Candace S
- [ ] Run J
- [ ] Nick V
- [ ] Laura E

#### Proposed changes

I have emails for Run and Nick. Sent Laura a message. @cansavvy can you provide a current email please 😀

**Comment by cansavvy** [comment]
csavonen@fredhutch.org Thanks!
