### ISSUE TITLE
Methods: Addl Sequencing Info from TGEN

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/OpenPBTA-manuscript#32]
We are expecting more info from TGEN. This issue is to track the receipt of that.

https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/31#discussion_r317092380

**Comment by jharenza** [comment]
This was updated with [this PR](https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/37)
