### ISSUE TITLE
Create TSV version of author information to make submissions easier

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#328]
We're planning to submit to _bioRxiv_ and _Cell Genomics_ at or very close to the same time. Right now, the author information is in YAML format ([`content/metadata.yaml`](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/metadata.yaml)). Per a request from @jharenza, it'd be helpful to have a table of author information when we're filing submissions. 

The table should have the following columns:

| Name | Email address | Affiliations | ORCID |
|-------|---------------|------------|--------|

The `Affiliations` column values for authors with multiple affiliations should be separated by `;`. I expect this will be accomplished by parsing the YAML file (probably in R with the `yaml` library). 

I'm going to assign this to @sjspielman for next week to avoid holding this up with my meeting schedule. A heads up – the fact that not everyone has an ORCID prevented me from doing this in under 5 minutes when it first came up.

**Comment by jharenza** [comment]
Also note, and maybe goes without saying, but having this in the final author order would be ideal.

**Comment by sjspielman** [comment]
> it'd be helpful to have a table of author information when we're filing submissions.

Should this be in any specific format, e.g. markdown, tsv/txt, or xlxs?

**Comment by jharenza** [comment]
TSV is fine!
