### ISSUE TITLE
Abbreviations to define

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/OpenPBTA-manuscript#33]
Certain abbreviations are widely used in the manuscript and will need to be described when first used. If you add one (or see one) in a section, please note it here.

**Comment by jharenza** [comment]
WXS = whole exome sequencing

**Comment by jharenza** [comment]
TPM = Transcripts Per Million mapped reads
FPKM = Fragments Per Kilobase of transcript per Million mapped reads

**Comment by jharenza** [comment]
closing this in favor of #166
