### ISSUE TITLE
Make author contributions consistent

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#334]
Currently, author contributions are one of the following, and some are duplicated or misspelled:
 
```
library(tidyverse)
dat <- yaml::read_yaml("metadata.yaml")

map_dfr(dat$authors, magrittr::extract, "contributions") %>% 
   distinct(contributions) %>% 
   arrange(contributions)
# A tibble: 19 × 1
   contributions               
   <chr>                       
 1 Conceptualization           
 2 Data curation               
 3 Data Curation               
 4 Formal analysis             
 5 Formal Analysis             
 6 Funding acquisition         
 7 Investigation               
 8 Methodology                 
 9 Project administration      
10 Resources                   
11 Software                    
12 Supervision                 
13 Supervison                  
14 Validation                  
15 Visualization               
16 Writing - Original draft    
17 Writing - Review and editing
18 Writing – original draft    
19 Writing – review & editing  
```

We need to clean this up. I will make the following changes:

`Data Curation` -> `Data curation`
`Formal Analysis` -> `Formal analysis`
`Supervison` (typo) -> `Supervision`
`Writing – original draft` -> `Writing – Original draft`
`Writing – review & editing` -> `Writing – Review and editing`

**Comment by sjspielman** [comment]
I was going to do this now, but there will likely be a bunch of conflicts with a lot of the incoming PRs. So I will wait on this for after more edits come in, closer to time of submission.

**Comment by jharenza** [comment]
@sjspielman I can take this tonight, once all of these merges go through. Will update with #332
