### ISSUE TITLE
ChimerDB Metadata Incorrect

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/OpenPBTA-manuscript#35]
It looks like the journal or publisher is not maintaining the correct metadata in crossref, as @jharenza noted in #34. I was going to email the journal, but there are 32,000 cases of this so a tweet seemed more likely to solve the broader problem:

https://twitter.com/GreeneScientist/status/1164881864009502720?s=20

**Comment by jharenza** [comment]
looks like this reference is no longer in the manuscript, so closing
