### ISSUE TITLE
Remove html tags from references

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenPBTA-manuscript#358]
Originally noted by @jharenza in  https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/310:
> A few refs have html italic/superscript tags, not sure if that is an issue, just pointing out here:
>
> * Duchemann, B., Naigeon, M., Auclin, E., Ferrara, R., Cassard, L., Jouniaux, J.-M., Boselli, L., Grivel, J., Desnoyer, A., Danlos, F.-X., et al. (2022). CD8+PD-1+ to CD4+PD-1+ ratio (PERLS) is associated with prognosis of patients with advanced NSCLC treated with PD-(L)1 blockers. J Immunother Cancer 10, e004012. https://doi.org/10.1136/jitc-2021-004012.
> * Guha, T., and Malkin, D. (2017). InheritedTP53Mutations and the Li–Fraumeni Syndrome. Cold Spring Harb Perspect Med 7, a026187. https://doi.org/10.1101/cshperspect.a026187.
> * Pfaff, E., Remke, M., Sturm, D., Benner, A., Witt, H., Milde, T., von Bueren, A.O., Wittmann, A., Schöttler, A., Jorch, N., et al. (2010). TP53 Mutation Is Frequently Associated With CTNNB1 Mutation or MYCN Amplification and Is Compatible With Long-Term Survival in Medulloblastoma. JCO 28, 5188–5196. https://doi.org/10.1200/jco.2010.31.1670.
> * Ramkissoon, L.A., Horowitz, P.M., Craig, J.M., Ramkissoon, S.H., Rich, B.E., Schumacher, S.E., McKenna, A., Lawrence, M.S., Bergthold, G., Brastianos, P.K., et al. (2013). Genomic analysis of diffuse pediatric low-grade gliomas identifies recurrent oncogenic truncating rearrangements in the transcription factor MYBL1. Proc. Natl. Acad. Sci. U.S.A. 110, 8188–8193. https://doi.org/10.1073/pnas.1300252110.

While we can fix these with manual references, it is probably just as easy to make the fix in the final submission document(s), which would allow us to add back the formatting that the html tags were trying to implement.

**Comment by jharenza** [comment]
I did update these in the submission manually.
