### ISSUE TITLE
Implement manuscript revisions and re-submit

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#364]
This Epic will track progress towards implementing the first (🤞 only) round of manuscript revisions and addressing reviewer comments, as well as associated logistics needed for re-submission.

**Comment by sjspielman** [comment]
Noting that issues which are specifically derived from reviewer comments are named beginning with `Revision:`.

**Comment by jharenza** [comment]
closed with #399
