### ISSUE TITLE
Revision: Indicate novel vs recapitulated findings

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#365]
Throughout the manuscript when findings are reported, we should clarify whether they are a) new and/or to our knowledge not previously observed, or b) previously observed and/or in-line with expectations from previous research.

**Comment by sjspielman** [comment]
This is partly addressed in #394 - https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/394#issuecomment-1406572880.

We should again go over the manuscript to specifically check for these kinds of spots.

**Comment by sjspielman** [comment]
@jharenza I've gone through the paper at its current version and I don't see too many more places to add this to. I've found a couple that we might add, if you have any feedback! If any of these make sense to you, I'll go ahead and add them in.

- `10.1080/14728222.2018.1487953` - introduces that ATRX is common in glioma
	- https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/59bd10e225eff961b3b9a92c01e21629e0cbdbaf/content/03.results.md?plain=1#L146
- `doi.org/10.1038/nature13109` - this paper just introduces that this fusion is common. This one I'm not sure we really need?
	- https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/59bd10e225eff961b3b9a92c01e21629e0cbdbaf/content/03.results.md?plain=1#L153
- `0.1200/JCO.2010.31.1670` - shows that CTNNB1-TP53 often co-occur in MB
	- https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/59bd10e225eff961b3b9a92c01e21629e0cbdbaf/content/03.results.md?plain=1#L169
- `10.1038/nrc3410` - shows that DDX3X is second most commonly mutated after CTNNB1 in MB
	- https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/59bd10e225eff961b3b9a92c01e21629e0cbdbaf/content/03.results.md?plain=1#L169

**Comment by jharenza** [comment]
These look good - note: 
>0.1200/JCO.2010.31.1670 - shows that CTNNB1-TP53 often co-occur in MB

should be `10.1200/JCO.2010.31.1670` - shows that CTNNB1-TP53 often co-occur in MB
