### ISSUE TITLE
Revision: Explore sequencing center batch effects

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#366]
Concerns were raised that batch effects specifically between CBTTC and PNOC might be present. We'll need to explore this a bit but also contextualize why we don't anticipate that it is a major confounder.

- First, we expect (and have observed) that stranded vs. polyA is the dominant batch effect for RNA-seq data
- Since samples are limited _within_ histologies, we'll want to check how prevalent it is to even see the same histology/technology (e.g. WGS vs RNAseq) grouped across centers. The data may show, for example, that all samples of a given histology analyzed with given tech same from the same center, making much of this specific batch effect concern moot.
  -  We could do a quick barplot of this, too, I think.
- If we see a lot of histologies _across_ centers, a viz such as UMAP colored by center will be helpful. Specifically, we'd want to make this for histologies that are shared across centers/tech.

**Comment by jharenza** [comment]
I am going to close this, as it is addressed solely in the response
