### ISSUE TITLE
Revision: Explain patient identifiability issues

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#367]
Reviewer comment suggested that we may want to include additional metadata clarifying which specific biosamples and/or patient IDs were profiled by different omics technologies. While we may want to expand on this somewhat, we want to be clear that one of our goals is to maintain anonymity of patients. It's possible someone could figure out the identify of a patient based on combined info of histology and sequencing locations, and we want to limit the chances of this happening.

**Comment by jharenza** [comment]
This is addressed in reviewer comments - do not think we need to put this in the manuscript.
