### ISSUE TITLE
Revision: Update Table 1

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#369]
A request was made for Table 1 to include two columns for N: one for patient and one for sample.

As needed, be aware of patient confidentially issues as described in #367.

**Comment by sjspielman** [comment]
This was completed by the following PRs:

- https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1643 
- #394

**Comment by sjspielman** [comment]
I'm re-opening this issue so we can make sure it is included in the response to reviewers. Please close this when we confirm it's in the response in it's final form.

**Comment by jharenza** [comment]
this is in the response....
