### ISSUE TITLE
Revision: Acknowledge other CBTN projects

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#373]
A reviewer comment pointed out that CBTN.org lists additional scientific projects, both completed and ongoing, utilizing the CBTN data. We want to make sure we acknowledge this in line with the open-science goals of this project.

**Comment by sjspielman** [comment]
This was possibly entirely addressed in #394, but scope for this review is a bit unclear. 
See https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/394#issuecomment-1406572880 and https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/394#issuecomment-1408759761.

**Comment by jharenza** [comment]
I think that this is fine to close, we have acknowledged a lot of these in discussion via pubs and noted the numbers
