### ISSUE TITLE
Revision: Clarify which samples were analyzed where

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#376]
- Clarify in the text that we do not have sufficient longitudinal samples to assess changes molecular changes in samples.
  - Relevant notebook: https://alexslemonade.github.io/OpenPBTA-analysis/analyses/sample-distribution-analysis/03-tumor-descriptor-and-assay-count.nb.html
- Clarify that primary samples were generally used. Related to #368

**Comment by jharenza** [comment]
>Clarify in the text that we do not have sufficient longitudinal samples to assess changes molecular changes in samples.

This is part of the response now

>Clarify that primary samples were generally used. 

Was merged in with #394 - under "### Somatic Mutational Landscape of Pediatric Brain Tumors":
>Unless otherwise noted, each analysis was performed for primary tumors using one tumor per patient.
