### ISSUE TITLE
Revision: Consider accounting for tumor purity

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#377]
A reviewer comment suggested we consider tumor purity (which is present in the main histologies file) when assessing the transcriptomic landscape. Relevant analyses include:
- GSVA
- EXTEND
- _tp53_ classifier

We can also consider reporting more summary stats about tumor purity, e.g. mean/median and SD/range, and assess whether tumor purity is correlated to histology.

**Comment by sjspielman** [comment]
Note that we may to break this issue up as we begin exploring it, but I suspect we'll end up seeing a couple separate issues in [AlexsLemonade/OpenPBTA-analysis](https://github.com/AlexsLemonade/OpenPBTA-analysis) to actually implement analyses.

**Comment by sjspielman** [comment]
Much work has been done towards this issue over in the [`OpenPBTA-analysis`](https://github.com/AlexsLemonade/OpenPBTA-analysis/) repository. For relevant transcriptomic modules, we analyzed, both quantitatively and qualitatively, how results might change if only stranded RNA-Seq library samples that pass a cancer-group-specific tumor purity threshold are considered. Broadly speaking, results are consistent with this filtered dataset. 

A tumor purity exploration module was established to begin this process: 
- https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1622
- https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1663

Analysis were/are being updated:
- GSEA: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1659
- Immune deconvolution: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1660
- telomerase: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1657
- TP53 (_in progress_): https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1664

**Comment by jharenza** [comment]
Noting here: The median tumor fraction for both WGS and stranded RNA-Seq samples was 0.76.

**Comment by jharenza** [comment]
Will add this info into response, rather than text - purity is listed in text now in #405

**Comment by sjspielman** [comment]
I want to note that we have a pending supplementary figure that needs to be mentioned in the response. It probably won't be in the MS due to restrictions, but we can still point to it - https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1684

**Comment by jharenza** [comment]
I think we are good with this one, all incorporated into the response
