### ISSUE TITLE
Revision: Clarify co-occurrence analysis

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#378]
We want to be clear that there are highly disparate sample sizes across histologies, and results are likely driven by predominating histologies (here, it's usually HGG tumors).
In addition, we'll want to clarify that CIs are large because the number of mutations for a given gene, across the cohort, is necessarily very small. Small sample sizes are the cause of large CIs.

**Comment by jharenza** [comment]
>We want to be clear that there are highly disparate sample sizes across histologies, and results are likely driven by predominating histologies (here, it's usually HGG tumors).

This was completed in #394 

>In addition, we'll want to clarify that CIs are large because the number of mutations for a given gene, across the cohort, is necessarily very small. Small sample sizes are the cause of large CIs.

This is addressed in response
