### ISSUE TITLE
Revision: Clarify how analyses relate to data releases

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#379]
Add text to explain that all analyses are performed with the latest data release, and there is a tagged release on github/zenodo corresponding to submission. 
We also want to clarify that analyses are not necessarily conducted in the cloud, but can often be run locally (depending on memory/storage requirements). The key is that analyses are run in _docker_, which is a container, not a cloud platform.

While discussing data releases, we'll also want to note that we did not generate the raw data, and we are not in charge of its provenance.

**Comment by jharenza** [comment]
This one was updated in #394 
>We reran all manuscript-specific analysis modules with the latest data release (v23) prior to submission and subsequently created a GitHub repository-tagged release to ensure reproducibility.
