### ISSUE TITLE
Revision: Clarify how we ensure result reproducibility

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#380]
A comment was raised about how reproducibility is assured when two separate groups analyze the same data. We'll want to emphasize that the code review process entails two or more analysts running the same code within the same docker container, which ensures reproducibility of results that are derived from the data release.

**Comment by sjspielman** [comment]
This was partly addressed in #394: https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/394#issuecomment-1406572880
More can always be added, but we have a lot there!! So, this is potentially all set?

**Comment by jharenza** [comment]
Closed with #405
