### ISSUE TITLE
Revision: WHO 2016 vs 2021

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#381]
Remove reference to WHO 2021 and stick with 2016.
Further, mention that are conservative in our subtyping approach, in part because IHC data is not available for these samples.

**Comment by sjspielman** [comment]
Noting from this comment that we will likely discuss IHC primarily in the response itself, but not the MS - https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/394#issuecomment-1407770003

**Comment by sjspielman** [comment]
Noting that associated manuscript changes were made in #394, as described:
- https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/394#issuecomment-1406572880
- https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/394#issuecomment-1407770003

However, we'll keep this issue open to ensure IHC etc. get discussed in the response.

**Comment by jharenza** [comment]
this has been incorporated into response
