### ISSUE TITLE
Revision: Expand TERT promoter mutation discussion

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#383]
We mention an exploration of TERT promoter mutations, but we do not follow-up clearly in results. To this end, we can also reference the EXTEND paper.

**Comment by sjspielman** [comment]
We have included some TERTp analysis here: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1653
Figure S5 was updated to highlight TERTp-positive samples here: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1655

**Comment by jharenza** [comment]
Closed with #405
