### ISSUE TITLE
Update Stephanie's contributions during revisions

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#387]
While working towards #191, I noticed that my contributions are not quite right. Let's address this during revisions.

Currently:
  - Validation
  - Formal analysis
  - Writing - Review and editing
  - Visualization
  - Supervision
  - Funding acquisition
  

Not clear to me that `Funding acquisition` should be there, but I guess I see an interpretation for why it shouldb be there! I did get money that did enable completion of the project, even though I didn't fund the overall OpenPBTA itself. 

These should also be there:
- `Writing - Original draft`
- `Investigation`
- `Software` (_maybe_. honestly never been quite sure what this precisely means! I did not write, eg, an R package, so maybe not?) (edited for all kinds of typos])

**Comment by jaclyn-taroni** [comment]
> I did get money that did enable completion of the project, even though I didn't fund the overall OpenPBTA itself.

Yea, that meets the criterion for `Funding acquisition`

**Comment by sjspielman** [comment]
@jaclyn-taroni Thoughts on whether I did software...?

**Comment by jaclyn-taroni** [comment]
Looking at how we use `Software` in the author list currently, yes I believe you "did software."
