### ISSUE TITLE
Revision: add text about tumor purity at DNA vs RNA-levels

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#392]
As part of revisions in the manuscript, we'll want to explicitly state that tumor purity values considered are derived from DNA, not RNA, even when applied to transcriptomics-level analyses. We do this only for co-extracted samples. We'll may want to explain in the text as well that frameworks like ESTIMATE for deriving RNA-level tumor purity from expression data are not necessarily appropriate for the tumors types in our cohort.

**Comment by jharenza** [comment]
>We'll may want to explain in the text as well that frameworks like ESTIMATE for deriving RNA-level tumor purity from expression data are not necessarily appropriate for the tumors types in our cohort.

We can add this in the response. We do state that Theta2 is used for purity from WGS samples. I put a small mention in the methods that we make the assumption that co-extracted samples have the same purity, but don't think we need to complicate the manuscript by mentioning any of the thresholded analyses- we can put that all in the response.

**Comment by jharenza** [comment]
Closed with #405
