### ISSUE TITLE
Updated manuscript: add Noel Coleman and Greg Way to author list

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#393]
#### What section of the manuscript should be updated?

authorship yaml file.

#### Proposed changes
Add @gwaybio and Noel Coleman to the author list.

Noel: 0000-0001-6454-1285 for data curation

@gwaybio can you add yourself for Investigation (?) and Writing - Review and Editing?

#### Relevant literature

_If there is relevant scientific literature, put links to those items here._

**Comment by jharenza** [comment]
Also add Chris Blackden for devops support

**Comment by jaclyn-taroni** [comment]
@gwaybio where you end up in the author order will be ultimately set programmatically – either based on the number of analysis modules in the paper you contributed to or randomly if you didn't have any (direct) contributions to the codebase. 

From [Author Contributions](https://alexslemonade.github.io/OpenPBTA-manuscript/#author-contributions):

> Except for the first and last four authors, authorship order was determined as follows: Authors who contributed to the OpenPBTA code base are listed based on number of modules included in the manuscript to which that individual contributed and, in the case of ties, a random order is used. All remaining authors are then listed in a random order.
>
> Code for determining authorship order can be found in the `count-contributions` module of the OpenPBTA analysis repository.

So if it's easier for you, you can feel free to put yourself wherever and the weekly cron job we use for this will sort you somewhere based on that criteria. Let me know if you have any questions.

**Comment by gwaybio** [comment]
Cool! I'll put myself smack in the middle for now. Thanks again!

**Comment by jharenza** [comment]
closed with #396
