### ISSUE TITLE
Revision: Add text for PNOC vs CBTTC

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#397]
The first paragraph in `Results` should include an explicit statement about how many samples were from each original cohort.

**Comment by sjspielman** [comment]
These edits were implemented in the manuscript in #394, as described in https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/394#issuecomment-1406572880.

**Comment by jharenza** [comment]
>We previously performed whole genome sequencing (WGS), whole exome sequencing (WXS), and RNA sequencing (RNA-Seq) on matched tumor and normal tissues as well as selected cell lines [@doi:10.1093/neuonc/noz192] from 943 patients from the Pediatric Brain Tumor Atlas (PBTA), consisting of 911 patients from the [Children’s Brain Tumor Network (CBTN)](https://CBTN.org) [@doi:10.1016/j.neo.2022.100846] and 32 patients from the [Pacific Pediatric Neuro-Oncology Consortium (PNOC)](https://pnoc.us/) [@doi:10.1002/ijc.32258; @doi:10.1158/1078-0432.CCR-22-0803] (**Figure {@fig:Fig1}A**).
