### ISSUE TITLE
Revision: Update tp53 p-value

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#400]
This text P-value is outdated (correct in the figure!). It should be **0.92**.
https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/33c98980d39dfc8b6c63691c819f8140f349c149/content/03.results.md?plain=1#L204

It was 0.23 back in April 2022 https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/33c98980d39dfc8b6c63691c819f8140f349c149/content/images/main/Figure4.png

But re-analysis by July 2022 saw it updated to 0.92. https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/e4244a104183e5223bc5297df938f8b5e6c7ef22/figures/pdfs/fig4/panels/tp53_scores_by_altered_panel.pdf

**Comment by jharenza** [comment]
closed with #405
