### ISSUE TITLE
Updated manuscript: check co-occurrence Ns and stats

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#410]
#### What section of the manuscript should be updated?

Results - we should check these numbers due to change in independent specimens

**Comment by sjspielman** [comment]
I've gone through numbers as shown below. _All_ numbers need to be tweaked as follows:

https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/789f65de824dcc28688d2751c0978bc6f86cb805/content/03.results.md?plain=1#L165
- Should be 668 now
	- In review: https://htmlpreview.github.io/?https://github.com/sjspielman/OpenPBTA-analysis/blob/interaction_numbers/analyses/interaction-plots/02-result-ns-for-manuscript.nb.html
- `(8.4%, 56/666)` —> `8.7% (58/668)`
	- 	In review: https://htmlpreview.github.io/?https://github.com/sjspielman/OpenPBTA-analysis/blob/interaction_numbers/analyses/interaction-plots/02-result-ns-for-manuscript.nb.html
- `_H3F3A_ (OR = 32, 95% CI: 15.3 - 66.7, q = 8.46e-17)`  —>  `_H3F3A_ (OR = 30.05, 95% CI: 14.5 - 62.3, q = 2.34e-16)`
- `_ATRX_ (OR = 20, 95% CI: 8.4 - 47.7, q = 4.43e-8)` —>  `_ATRX_ (OR = 23.3, 95% CI: 9.6 - 56.3, q = 8.72e-9)`
- `_NF1_ (OR = 8.62, 95% CI: 3.7 - 20.2, q = 5.45e-5)` —> `_NF1_ (OR = 8.26, 95% CI: 3.5 - 19.4, q = 7.40e-5)`
- `_EGFR_ (OR = 18.2, 95% CI: 5 - 66.5, q = 1.6e-4)` —> `_EGFR_ (OR = 17.5, 95% CI: 4.8 - 63.9, q = 2e-4)`
	- https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/732d07cd2946849c6b5809e364043b390f85a2ed/analyses/interaction-plots/results/cooccur_top50.ALL.tsv

https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/789f65de824dcc28688d2751c0978bc6f86cb805/content/03.results.md?plain=1#L169
- This sentence needs to be updated to say “embryonal” not “mb” which is a cancer group within the embryonal broad histology.
- CTNNB1 `(OR = 42.9, 95% CI: 7 - 261.4, q = 1.63e-3)` —> `(OR = 43.6 95% CI: 7.1 - 265.8, q = 1.52e-3)`
- _DDX3X_ `(OR = 21.1, 95% CI: 4.6 - 96.3, q = 4.46e-3)` —> `(OR = 21.4, 95% CI: 4.7 - 97.9, q = 4.15e-3)`

https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/789f65de824dcc28688d2751c0978bc6f86cb805/content/03.results.md?plain=1#L170
- `OR = 76.1, 95% CI: 9.85 - 588.1, q = 3.26e-3)` —> `OR = 77.25, 95% CI: 10.0 - 596.8, q = 3.12e-3)`

https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/789f65de824dcc28688d2751c0978bc6f86cb805/content/03.results.md?plain=1#L171
- `52/54 (96.3%)` —> `53/55 (96.3%)`
- `(OR = 0.188, 95% CI: 0.04 - 0.94, p = 0.0413, q = 0.0587)` —> ` (OR = 0.17, 95% CI: 0.04 - 0.89, q = 0.056)` 
	- https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/732d07cd2946849c6b5809e364043b390f85a2ed/analyses/interaction-plots/results/cooccur_top50.Diffuse-astrocytic-and-oligodendroglial-tumor.tsv
