### ISSUE TITLE
Add Figure S7 to manuscript

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#421]
Once https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1691 is completed, we need to add Figure S7 to the manuscript in `content/07.supplemental.md`; the scope of this includes writing a legend. Previously, we did not include Figure S7 in the manuscript.

**Comment by jharenza** [comment]
closed with #435
