### ISSUE TITLE
Add text about RNA-seq batch effects to discussion section as part of limitations of the study

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#422]
We have two separate RNA-seq library preparation strategies (poly-A and stranded) under the PBTA umbrella. 

We don't combine these because there's a clear batch effect (from `v5` when these were still combined for release: https://alexslemonade.github.io/OpenPBTA-analysis/analyses/selection-strategy-comparison/01-selection-strategies.nb.html#raw_clustering). The disease types are also unbalanced between the poly-A and stranded datasets (older `v5` disease labels: https://alexslemonade.github.io/OpenPBTA-analysis/analyses/selection-strategy-comparison/01-selection-strategies.nb.html#sample_info), and we have some concern about inducing false differences between groups with a batch correction strategy ([ref](https://doi.org/10.1093/biostatistics/kxv027)). 

More generally, though, batch correction strategies should be dependent on the experimental question at hand ([ref](https://doi.org/10.1016/j.tibtech.2017.02.012)), and we can't provide one batch corrected dataset that's going to be appropriate for every analysis. 

We'll have a new display item that covers these points (https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1691), but we should also note this as a limitation of the study in the Discussion section.

**Comment by jharenza** [comment]
closed with #435
