### ISSUE TITLE
Clarify what we mean by "stranded" RNA-seq dataset and explain rationale for using it for most of the txomic analyses

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#423]
* We could be more clear about what we mean by stranded sample prep: https://alexslemonade.github.io/OpenPBTA-manuscript/#cbtn-samples (for one thing, it'd be good to re-iterate ribodepletion and also fix the subscript issue!)
* Although we repeatedly mention which dataset we use in the methods section (https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/770034a7feed1ccee9fe200c3013db6419ee671e/content/06.methods.md#quantification-and-statistical-analysis), there isn't anything about our dataset selection in what I think is the most relevant Results section: https://alexslemonade.github.io/OpenPBTA-manuscript/#transcriptomic-landscape-of-pediatric-brain-tumors

**Comment by jharenza** [comment]
> also fix the subscript issue!

ha, I noticed this recently, as well!
