### ISSUE TITLE
Meet 7000 word limit

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#432]
These sections count towards the 7000 word limit:

* Summary
* Intro
* Results
* Discussion
* Limitations
* Figure Legends
* Acknowledgements

STAR Methods _does not_ count towards the word limit. We have been advised that it might be helpful to move methods description that may be in the results into STAR Methods to meet this word limit.

**Comment by sjspielman** [comment]
As of [d3fc90](https://github.com/AlexsLemonade/OpenPBTA-manuscript/commit/d3fc90c9c2c77bf76fa3a4dafee96fb4b1bb1024) we have:

|Section|count|
|------|--------|
| Summary | 137 |
| Introduction | 590 |
| Results | 3963 |
| Discussion | 1216 |
| Limitations | 335 |
| Legends | 1055 |

**Total is 7296** which is getting close!!

**Comment by jharenza** [comment]
Also need to add acknowledgements @sjspielman - I forgot that initially! 😬

**Comment by sjspielman** [comment]
After #449, we're down to ~7110.
