### ISSUE TITLE
Update oncoplot descriptions

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#444]
From this comment: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1713#issuecomment-1485141891

There are not always N=20 genes in the oncoplots, for cases when <20 samples have >1 alteration. This needs to be clarified in the manuscript text.

**Comment by jharenza** [comment]
Hi @sjspielman I was going to update this but might still need clarification. I'm confused about how there are "NA" genes when we only searched using genes of interest. And did you mean to say in cases where there are <1 (instead of >1) samples with an alteration, then we do not show them?

**Comment by sjspielman** [comment]
@jharenza this is the crux piece of code:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/cf6328ebd7c3bdffa18b4bd6b8d856713a8414aa/figures/scripts/fig2_figS3-oncoprint-landscape.R#L76-L78

The GOI apparently do not exist in multiple samples, so even though we filter to some GOIs, it seems that some GOIs didn't even make it to that step...
