### ISSUE TITLE
Complete Inclusion and Diversity steps

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#457]
- [x] Use the survey responses from authors to draft an **Inclusion and Diversity** section, positioned directly after the **Declarations of Interest** section, provided no author replied to object
- [x] Complete the [Inclusion and Diversity Form](https://www.cell.com/pb/assets/raw/shared/forms/IandDstatement_form.pdf)

**Comment by jharenza** [comment]
completed
