### ISSUE TITLE
Create a graphical abstract

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#461]
Create a graphical abstract following the [Graphical Abstract Guidelines](https://www.cell.com/pb/assets/raw/shared/figureguidelines/GA_guide-1537202744020.pdf)

**Comment by jaclyn-taroni** [comment]
I am posting what I have at the moment

#### Context

* Request was to use CBTN colors
* The Cell Press guidelines say, "Authors are encouraged to select colors that are consistent with and complementary to the colors used on the Cell Press website. Heavily saturated, primary colors can be distracting."
  * The background colors come from the guidelines
* Idea from @jharenza and others was to have data come into a form (hourglass) and then be distributed to community, platforms, other projects.
* Guidelines also state that a clear reading should be in one direction. I've chosen top to bottom. The layout is obviously pretty inspired by the guidelines as well.
* Labels are very simple/light on text in accordance with guidelines.



![openpbta-graphical-abstract](https://user-images.githubusercontent.com/19534205/235251994-ccca1d45-9e43-4203-900a-b23d8c965ee5.png)

**Comment by jharenza** [comment]
It looks amazing and I think it captures the essence of the project well! 👏
