### ISSUE TITLE
Updated manuscript: SNV Caller Methods

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-manuscript#53]
#### Context

VarDict file is much larger than the other callers' files (~5x) as large and the VAF for the mutations called by VarDict are particularly low. It's been difficult getting this data because of how many mutations it calls that none of the other callers seem to call. 

#### What section of the manuscript should be updated?

[SNV caller mutations section](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/bb4c4096a6c361e36c194a778c4192a75984ece9/content/03.methods.md#snv-and-indel-calling) could use more details regarding their parameters and decisions that were made. 

Specifically could the information about VarDict be explained and linked to data/analyses? The manuscript says that keeping the low VAF increased true positive rate for INDELS? 

> The 0.05 VAF increased the true positive rate for INDELs and decreased the false positive rate for SNVs when using VarDict in consensus calling.

**Comment by jharenza** [comment]
@yuankunzhu and @migbro - can you help with this?

**Comment by jharenza** [comment]
@migbro - can you comment?

**Comment by migbro** [comment]
Hi @cansavvy , this was based on some internal benchmarking in which we compared each tool, and as a consensus of two or more to the ICGC bechmarking dataset.  They had WGS and targeted sequencing on 42 patients with various cancers, and we had access to their alignment data and calls.  When I had filtered on the 10% maf, for VarDict, I had notices a slight drop in TP calls based on their consensus call set.  However, I don't think this means that when it comes to consensus calling, or to used of the data for the tool, that applying a VAF or any additional filters is out of the question. There aren't relly plans to write a benchmarking paper that we could point to, as the efforts of ICGC aren't published yet either; it'd be a bit underhanded if we wanted to to publish on their data, probably couldn't without their consent anyway.  Regardless, the exercise was really to try and balance giving the end user something workable, not quite to make their decisions for them. In short, this is the best we have for right now, and we are erring on the side of sensitivity over specificity, and leaving it to the analyst to really get in there and suss it out. Does that sound accurate @yuankunzhu, or do we have plans to go a little deeper into VarDict calls?

**Comment by jharenza** [comment]
@jaclyn-taroni @jashapiro - For this, we could potentially write about internal benchmarking, and/or create a slide deck to link them? Not sure how to go about this one since most is unpublished.

**Comment by jharenza** [comment]
@cansavvy - not sure we have more to add here?

**Comment by jharenza** [comment]
@cansavvy - do you still think we need more information here?

**Comment by jharenza** [comment]
closing due to #61
