### ISSUE TITLE
Updated manuscript: Consensus SNV calls

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#60]
#### What section of the manuscript should be updated?

_Add the section (and subsection) needing an update._
[Methods - somatic mutation calling](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#somatic-mutation-calling) - Create a consensus SNV sub-section

#### Proposed changes

_What changes need to be made and/or what details are missing?_
_Explain your rationale for the update._
_Please include a level of detail that will allow another participant to make the update._
Add details surrounding consensus SNV calls we released with [V10](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/273)

#### Relevant literature

_If there is relevant scientific literature, put links to those items here._

**Comment by jaclyn-taroni** [comment]
I believe this was closed via #66
