### ISSUE TITLE
Updated manuscript: Indicate when methods were run selectively (e.g., WGS data only)

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#69]
#### What section of the manuscript should be updated?

The methods section - https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md
And at least the somatic CNV and SV sections: https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#somatic-copy-number-variant-calling, https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#somatic-structural-variant-calling

#### Proposed changes

The caveats listed here should be included in the CNV and SV subsections: https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/436#issuecomment-574445530

If there are any additional cases like this (for example, something was only run on poly-A samples), we should document them as well.

#### Relevant literature

N/A

**Comment by jharenza** [comment]
closed via #74
