### ISSUE TITLE
Updated manuscript: add TCGA SNV calling methods

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#71]
#### What section of the manuscript should be updated?
SNV Calling methods

#### Proposed changes
Add TCGA SNV calling for Mutect2, Strelka2, Lancet

#### Relevant literature

_If there is relevant scientific literature, put links to those items here._

**Comment by jharenza** [comment]
Note: references are [here](https://cavatica.sbgenomics.com/u/cavatica/openpbta-tcga/files/#q?search=GRCh38.d1.vd1), but we need public links. cc @migbro @tkoganti

**Comment by tkoganti** [comment]
How BED file was prepared - 
This was created from gencode.v19.basic.exome.bed in this page - https://gdc.cancer.gov/about-data/publications/mc3-2017

Used liftover tool online to convert to Gh38
Added 100bp on either side
Used samtools sort to sort the BED file
Used samtools merge to merge overlapping regions
Removed contig chromosomes

New BED file named as `gencode.v19.basic.exome.hg38liftover.bed` and uploaded to S3 bucket under TCGA folder

**Comment by jharenza** [comment]
@tkoganti and @yuankunzhu, just getting this back on your radar once the samples are finished running. Of course, some of the above is now old and no longer valid. Let me know if you would like me to help as well.

**Comment by cansavvy** [comment]
@tkoganti and @yuankunzhu, it looks like this has made some progress with #88 ! It seems that before we can close this issue we could use some more information/clarification about the following in the methods section: https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#snv-and-indel-calling

- Although there's more description around WGS SNV caller parameters, there doesn't seem to be as much description or clarification about WXS SNV callers, except for the note about the 100 bp padding. If the parameters were exactly the same except for padding, can we make that more clear? If the parameters were not the same, can we make those distinctions? 

- Can we add more about the [TCGA BED methods like what is described in the comment above](https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/71#issuecomment-589168656) but for what is up to date with what went on with https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/568 ?  In the methods as they are now, it makes it sound like the files were directly downloaded from GDC and that is all. This includes perhaps having a note about the genome builds for TCGA vs PBTA and the liftover step.  

- Can the WXS target manufacturers listed for the TCGA data should be listed more specifically and cited?

**Comment by cansavvy** [comment]
Through Slack, @tkoganti and I discussed adding a quick summary of this analysis: https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/tcga-capture-kit-investigation as well as summaries of the items discussed above.

**Comment by tkoganti** [comment]
@cansavvy I am not seeing an option to add reviewers but  here is a pull request where I updated the data descriptions - https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/677

**Comment by jharenza** [comment]
added with #88
