### ISSUE TITLE
Updated manuscript: Add germline BAF methods

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#73]
#### What section of the manuscript should be updated?
CNV calling

#### Proposed changes
The input for copy number is not documented, nor references for it

#### Relevant literature
NA

@migbro will work on this

**Comment by migbro** [comment]
PR to address this has been made [here](https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/85), but need assistance troubleshooting a circle CI error.

**Comment by jharenza** [comment]
closed with #85
