### ISSUE TITLE
Methods: chromothripsis analysis / ShatterSeek

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#75]
Related to: https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/393

In https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/449, @yangyangclover is adding a modified ShatterSeek approach to identify chromothripsis events in the PBTA dataset. This approach will need to be described in the methods section.

**Comment by jharenza** [comment]
@LauraEgolf could you work on this once your analysis is completed?

**Comment by LauraEgolf** [comment]
Yes, will take care of this section.
