### ISSUE TITLE
Methods: molecular subtyping for HGG and embryonal tumors

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#82]
#### What section of the manuscript should be updated?
Molecular subtyping

#### Proposed changes
Include methods for [HGG subtyping](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-HGG) and [embryonal tumor](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-embryonal) subtyping.

#### Relevant literature

_If there is relevant scientific literature, put links to those items here._

**Comment by jaclyn-taroni** [comment]
I'm going to call this closed via #86.
