### ISSUE TITLE
Figure panel: Flowchart showing project features

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#83]
From the proposed sketch of Figure 1:

![project-features-flowchart](https://user-images.githubusercontent.com/19534205/75586797-1a5f8e00-5a43-11ea-91a2-f3ae22b584fc.png)

Here's a (odd formatted preview of) slide from @jashapiro's Rocky talk:

<img width="1039" alt="Screen Shot 2020-02-28 at 4 00 09 PM" src="https://user-images.githubusercontent.com/19534205/75586956-6ca0af00-5a43-11ea-8643-81877ba7dccf.png">

It displays the same information we want to convey but we'll probably want less text in this context!

**Comment by jharenza** [comment]
Completed with [#1292](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1292)
