### ISSUE TITLE
Figure panel: mutational landscape

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-manuscript#84]
I will file the figure for [Results - Mutational Landscape section](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/04.results.md#landscape-of-mutational-processes) 

The figure sketch needs to be replaced with the plots with the data as they are now.

Related PR: https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/79

**Comment by jaclyn-taroni** [comment]
Closed via #89
