### ISSUE TITLE
Updated manuscript: CNV Consensus calls

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-manuscript#92]
#### What section of the manuscript should be updated?

The CNV section of the methods:
https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#somatic-copy-number-variant-calling-wgs-samples-only

#### Proposed changes

Include the relevant information from the CNV consensus README: https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/copy_number_consensus_call

#### Relevant literature

I don't know of any, but if anyone has suggestions.

**Comment by jashapiro** [comment]
From @hongboxie, here is one reference that will be important.

> Here is the paper we can reference for CNV excluded regions. 
>  White PS, Xie HM, Werner P, Glessner J, Latney B, Hakonarson H, Goldmuntz E.,Analysis of chromosomal structural variation in patients with congenital left-sided cardiac lesions. Birth Defects Res A Clin Mol Teratol. 2014 Dec;100(12):951-64. doi: 10.1002/bdra.23279. Epub 2014 Jul 26.

I would expect he and @fingerfen may have other resources worth citing.

**Comment by jaclyn-taroni** [comment]
Was this closed by #93 or is there more to be done?

**Comment by jaclyn-taroni** [comment]
Closed by #93
