### ISSUE TITLE
Information to redo alignment

### ISSUE THREAD

**Issue by KimHoaHo** [AlexsLemonade/OpenPBTA-manuscript#97]
Hello

I have downloaded WGS and RNAseq data of human choroid plexus papilloma and carcinoma data from CBTTC database (.bam files of aligned reads). I need to transfer these files to our IT core facility to run some pipelines. Unfortunately, they only accepts .fastq files and need lots of information for managing the data as well as for realigning the reads. Ihave searched on the github site (https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md) but failed to identify any of this information. Here a detailed list of the requested missing information: 

1. Mate (This stands for the read the fastq file stands for, so 1, 2, i1, i2 respectively)
2. MD5 
3. BARCODE (the index used for sequencing)
4. PIPELINE_VERSION (software used for the conversion of the bcl files to fastq)
5. SEQUENCING_KIT (chemistry used for sequencing run)
6. INSTRUMENT_MODEL: this is confusing to us as I found on the github site that the instrument was HiSeq X/400. However, we're only aware of HiSeq X and HiSeq 4000. Could you please further explain on this?
7. Name of Index kit and adapter sequences

Could someone please help me me with this?
Thank you very much

**Comment by jaclyn-taroni** [comment]
Hi @KimHoaHo,

This is a manuscript repository for the Open Pediatric Brain Tumor Atlas project that does not include the BAMs file as part of the scope. I would suggest filing a support request with the repository or portal where you obtained the data. 

As a starting point, I might contact CBTTC via this web form: https://cbttc.org/about-cbttc/contact/ They will likely know where the best place to report this issue will be.

I'm also tagging @allisonheath and @yuankunzhu, who may have a better idea of where to file the issue than I do.

I'm going to close this issue, as it is beyond the scope of this repository. Thank you!
